name: API Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      api:
        image: timotejekart/dj-api:latest
        env:
          ASPNETCORE_ENVIRONMENT: Development
          ASPNETCORE_URLS: http://+:5152
          ConnectionStrings__DbConnection: ${{ secrets.MONGODB_CONNECTION_STRING }}
          JWTSecrets__issuer: ${{ secrets.JWT_ISSUER }}
          JWTSecrets__audience: ${{ secrets.JWT_AUDIENCE }}
          JWTSecrets__secretKey: ${{ secrets.JWT_SECRET_KEY }}
          JWTSecrets__expires: ${{ secrets.JWT_EXPIRES }}
        ports:
          - 5152:5152

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET 8
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Wait for API
        run: sleep 10

      - name: Run Tests
        env:
          ASPNETCORE_ENVIRONMENT: Development
          API_BASE_URL: http://localhost:5152
        run: dotnet test IntegrationTestsDjApi/IntegrationTestsDjApi.csproj -c Release
